### ISSUE TITLE
manual connect 

### ISSUE THREAD

**Issue by feof** [rodgc/ngx-socket-io#23] opened 2018-12-11 14:16 UTC
Hi,
I have in my app.modules.ts this:
const config: SocketIoConfig = { url: `${environment.host}`, options: {} };
...
  imports: [
...    SocketIoModule.forRoot(config)
  ],

My socket.io be connected  at bootstrap. Can I connect socket manually ?
Tnx

**Comment by cristianfloresee** [comment] 2018-12-17 23:57
tengo la misma pregunta. con socket.io antes utilizaba 

```
import { environment } from 'src/environments/environment';
import * as io from 'socket.io-client';

export class SocketService {

   private socket;

   constructor(
      private client: HttpClient,
      ) { }

connectSocket() {
  this.socket = io(environment.apiUrl);
}

disconnectSocket() {
  if (this.socket) this.socket.disconnect();
}
```

**Comment by nihalmpatel** [comment] 2019-01-23 12:56
@feof The socket connection automatically establishes at bootstrap because of the configuration in App module. If you want to connect socket manually, a workaround could be to disconnect socket connection (```this.socket.disconnect()```) at bootstrap and connect (```this.socket.connect()```) again whenever it's needed.

**Comment by seba-salavilla** [comment] 2019-04-04 15:16
> Hi,
> I have in my app.modules.ts this:
> const config: SocketIoConfig = { url: `${environment.host}`, options: {} };
> ...
> imports: [
> ... SocketIoModule.forRoot(config)
> ],
> 
> My socket.io be connected at bootstrap. Can I connect socket manually ?
> Tnx

Yes you can, first add option autoConnect : false
`const config: SocketIoConfig = { url: ${environment.host}, options: { autoConnect : false } };`

then, in Socketservices.ts create a method Connect() with params as you want.
Now you can call the method and reconfigure the connections and options of socket instance.

Example:
```
Connect(options){
    this.socket.ioSocket.io.opts.query = { token: 'minuevotoken' } //new options
    this.socket.ioSocket.io.uri = "http://localhost:3001" //new uri
    this.socket.connect(); //manually connection
}
```

**Comment by neverovski** [comment] 2020-03-18 06:22
> > Hi,
> > I have in my app.modules.ts this:
> > const config: SocketIoConfig = { url: `${environment.host}`, options: {} };
> > ...
> > imports: [
> > ... SocketIoModule.forRoot(config)
> > ],
> > My socket.io be connected at bootstrap. Can I connect socket manually ?
> > Tnx
> 
> Yes you can, first add option autoConnect : false
> `const config: SocketIoConfig = { url: ${environment.host}, options: { autoConnect : false } };`
> 
> then, in Socketservices.ts create a method Connect() with params as you want.
> Now you can call the method and reconfigure the connections and options of socket instance.
> 
> Example:
> 
> ```
> Connect(options){
>     this.socket.ioSocket.io.opts.query = { token: 'minuevotoken' } //new options
>     this.socket.ioSocket.io.uri = "http://localhost:3001" //new uri
>     this.socket.connect(); //manually connection
> }
> ```
@seba-salavilla 
It works for me, thx.

**Comment by ctfrancia** [comment] 2020-04-28 21:32
I am going to close this issue as it has been 2 years, if the issue is still relevant please open up a new ticket

**Closed by ctfrancia** 2020-04-28 21:32 UTC

**Comment by LeonardoRick** [comment] 2020-10-08 19:02
This should be on docs, thanks a lot!!
